// This file is a sample seed data for the EHR field mappings for demo purposes.
// It contains mappings for two EHR providers: Athena and Allscripts.
export const ehrFieldMappings = [
  // Athena mappings
  {
    tenantId: 'clinic-123',
    ehrProvider: 'Athena',
    questionKey: 'name',
    endpoint: '/patient',
    ehrField: 'PATIENT_IDENT_NAME',
  },
  {
    tenantId: 'clinic-123',
    ehrProvider: 'Athena',
    questionKey: 'gender',
    endpoint: '/patient',
    ehrField: 'GENDER_OF_PATIENT',
  },
  {
    tenantId: 'clinic-123',
    ehrProvider: 'Athena',
    questionKey: 'dob',
    endpoint: '/patient',
    ehrField: 'DATE_OF_BIRTH_PATIENT',
  },
  {
    tenantId: 'clinic-123',
    ehrProvider: 'Athena',
    questionKey: 'address',
    endpoint: '/patient',
    ehrField: 'PATIENT_LOCATION_ADDRESS',
  },
  {
    tenantId: 'clinic-123',
    ehrProvider: 'Athena',
    questionKey: 'phone',
    endpoint: '/patient',
    ehrField: 'TELEPHONE_NUMBER_PATIENT',
  },
  {
    tenantId: 'clinic-123',
    ehrProvider: 'Athena',
    questionKey: 'email',
    endpoint: '/patient',
    ehrField: 'PATIENT_EMAIL_ID',
  },
  {
    tenantId: 'clinic-123',
    ehrProvider: 'Athena',
    questionKey: 'emergencyContact',
    endpoint: '/patient',
    ehrField: 'EMERGENCY_CONTACT_PATIENT',
  },
  {
    tenantId: 'clinic-123',
    ehrProvider: 'Athena',
    questionKey: 'insuranceProvider',
    endpoint: '/patient',
    ehrField: 'INSURANCE_PROVIDER_PATIENT',
  },
  {
    tenantId: 'clinic-123',
    ehrProvider: 'Athena',
    questionKey: 'insurancePolicyNumber',
    endpoint: '/patient',
    ehrField: 'POLICY_NUMBER_INSURANCE_PATIENT',
  },
  {
    tenantId: 'clinic-123',
    ehrProvider: 'Athena',
    questionKey: 'primaryCarePhysician',
    endpoint: '/patient',
    ehrField: 'PRIMARY_CARE_DOCTOR_PATIENT',
  },
  {
    tenantId: 'clinic-123',
    ehrProvider: 'Athena',
    questionKey: 'allergies',
    endpoint: '/patient',
    ehrField: 'ALLERGIES_PATIENT',
  },
  {
    tenantId: 'clinic-123',
    ehrProvider: 'Athena',
    questionKey: 'currentMedications',
    endpoint: '/patient',
    ehrField: 'PATIENT_MEDICATIONS_CURRENT',
  },
  {
    tenantId: 'clinic-123',
    ehrProvider: 'Athena',
    questionKey: 'medicalHistory',
    endpoint: '/patient',
    ehrField: 'HISTORY_MEDICAL_PATIENT',
  },
  {
    tenantId: 'clinic-123',
    ehrProvider: 'Athena',
    questionKey: 'socialHistory',
    endpoint: '/patient',
    ehrField: 'HISTORY_SOCIAL_PATIENT',
  },
  {
    tenantId: 'clinic-123',
    ehrProvider: 'Athena',
    questionKey: 'familyHistory',
    endpoint: '/patient',
    ehrField: 'HISTORY_FAMILY_PATIENT',
  },

  // Allscripts mappings
  {
    tenantId: 'clinic-123',
    ehrProvider: 'Allscripts',
    questionKey: 'name',
    endpoint: '/patient',
    ehrField: 'NAME_OF_PAT',
  },
  {
    tenantId: 'clinic-123',
    ehrProvider: 'Allscripts',
    questionKey: 'gender',
    endpoint: '/patient',
    ehrField: 'GENDER_PAT',
  },
  {
    tenantId: 'clinic-123',
    ehrProvider: 'Allscripts',
    questionKey: 'dob',
    endpoint: '/patient',
    ehrField: 'BIRTHDATE_OF_PAT',
  },
  {
    tenantId: 'clinic-123',
    ehrProvider: 'Allscripts',
    questionKey: 'address',
    endpoint: '/patient',
    ehrField: 'ADDRESS_PAT',
  },
  {
    tenantId: 'clinic-123',
    ehrProvider: 'Allscripts',
    questionKey: 'phone',
    endpoint: '/patient',
    ehrField: 'PHONE_NUMBER_PAT',
  },
  {
    tenantId: 'clinic-123',
    ehrProvider: 'Allscripts',
    questionKey: 'email',
    endpoint: '/patient',
    ehrField: 'EMAIL_ID_PAT',
  },
  {
    tenantId: 'clinic-123',
    ehrProvider: 'Allscripts',
    questionKey: 'emergencyContact',
    endpoint: '/patient',
    ehrField: 'EMERGENCY_CONTACT_PAT',
  },
  {
    tenantId: 'clinic-123',
    ehrProvider: 'Allscripts',
    questionKey: 'insuranceProvider',
    endpoint: '/patient',
    ehrField: 'PROVIDER_INSURANCE_PAT',
  },
  {
    tenantId: 'clinic-123',
    ehrProvider: 'Allscripts',
    questionKey: 'insurancePolicyNumber',
    endpoint: '/patient',
    ehrField: 'POLICY_NUM_INSURANCE_PAT',
  },
  {
    tenantId: 'clinic-123',
    ehrProvider: 'Allscripts',
    questionKey: 'primaryCarePhysician',
    endpoint: '/patient',
    ehrField: 'PRIMARY_CARE_DOC_PAT',
  },
  {
    tenantId: 'clinic-123',
    ehrProvider: 'Allscripts',
    questionKey: 'medicalHistory',
    endpoint: '/patient',
    ehrField: 'HISTORY_MEDICAL_PAT',
  },
  {
    tenantId: 'clinic-123',
    ehrProvider: 'Allscripts',
    questionKey: 'allergies',
    endpoint: '/patient',
    ehrField: 'ALLERGIES_PAT',
  },
  {
    tenantId: 'clinic-123',
    ehrProvider: 'Allscripts',
    questionKey: 'currentMedications',
    endpoint: '/patient',
    ehrField: 'CURRENT_MEDS_PAT',
  },
  {
    tenantId: 'clinic-123',
    ehrProvider: 'Allscripts',
    questionKey: 'socialHistory',
    endpoint: '/patient',
    ehrField: 'SOCIAL_HISTORY_PAT',
  },
  {
    tenantId: 'clinic-123',
    ehrProvider: 'Allscripts',
    questionKey: 'familyHistory',
    endpoint: '/patient',
    ehrField: 'FAMILY_HISTORY_PAT',
  },
];
