version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: previsit-questionnaire-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE:-previsit-questionnaire}
    volumes:
      - mongo_data:/data/db
    networks:
      - previsit-questionnaire-app-network

  redis:
    image: redis:7-alpine
    container_name: previsit-questionnaire-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - previsit-questionnaire-app-network

  previsit-api:
    build:
      context: .
      dockerfile: previsit-api/Dockerfile
    image: previsit-api
    container_name: previsit-questionnaire-api
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis
    environment:
      MONGODB_URI: ${MONGODB_URI}
      REDIS_URI: ${REDIS_URI}
      PORT: ${API_PORT:-3000}
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000/api/v1/health/check"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    networks:
      - previsit-questionnaire-app-network

  previsit-console:
    build:
      context: .
      dockerfile: previsit-console/Dockerfile
    image: previsit-console
    container_name: previsit-questionnaire-console
    ports:
      - "4001:3000"
    depends_on:
      previsit-api:
        condition: service_healthy
    environment:
      NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL:-http://previsit-api:3000/api}
    networks:
      - previsit-questionnaire-app-network

  previsit-app:
    build:
      context: .
      dockerfile: previsit-app/Dockerfile
    image: previsit-app
    container_name: previsit-questionnaire-app
    ports:
      - "4000:3000"
    depends_on:
      previsit-api:
        condition: service_healthy
    environment:
      NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL:-http://previsit-api:3000/api}
      NEXT_PUBLIC_CONSOLE_URL: ${NEXT_PUBLIC_CONSOLE_URL:-http://localhost:4001}
    networks:
      - previsit-questionnaire-app-network

volumes:
  mongo_data:
  redis_data:

networks:
  previsit-questionnaire-app-network:
    driver: bridge
