export const questionnaireSeedData = [
  {
    tenantId: 'clinic-123',
    name: {
      en: 'Patient Intake Form',
      es: 'Formulario de ingreso del paciente',
    },
    description: {
      en: 'General health and contact information for new patients',
      es: 'Información general de salud y contacto para nuevos pacientes',
    },
    submitButtonLabel: {
      en: 'Submit previsit form',
      es: 'Enviar el formulario',
    },
    isActive: true,
    questionKeys: [
      'name',
      'dob',
      'gender',
      'address',
      'phone',
      'email',
      'emergencyContact',
      'insuranceProvider',
      'insurancePolicyNumber',
      'primaryCarePhysician',
      'allergies',
      'currentMedications',
      'medicalHistory',
      'socialHistory',
      'familyHistory',
    ],
  },
  {
    tenantId: 'clinic-123',
    name: {
      en: 'Dental pre-Visit survey',
      es: 'Encuesta previa a la visita dental',
    },
    description: {
      en: 'General health and contact information for new patients',
      es: 'Información general de salud y contacto para nuevos pacientes',
    },
    submitButtonLabel: {
      en: 'Submit previsit form',
      es: 'Enviar el formulario',
    },
    isActive: true,
    questionKeys: [
      'name',
      'dob',
      'gender',
      'address',
      'phone',
      'email',
      'emergencyContact',
      'insuranceProvider',
      'insurancePolicyNumber',
      'primaryCarePhysician',
      'allergies',
      'currentMedications',
      'medicalHistory',
      'socialHistory',
      'familyHistory',
    ],
  },
  {
    tenantId: 'clinic-123',
    name: {
      en: 'Test visit form',
      es: 'Formulario de prueba',
    },
    description: {
      en: 'General health and contact information for new patients',
      es: 'Información general de salud y contacto para nuevos pacientes',
    },
    submitButtonLabel: {
      en: 'Submit previsit form',
      es: 'Enviar el formulario',
    },
    isActive: true,
    questionKeys: [
      'name',
      'dob',
      'gender',
      'address',
      'phone',
      'email',
      'emergencyContact',
      'insuranceProvider',
      'insurancePolicyNumber',
      'primaryCarePhysician',
      'allergies',
      'currentMedications',
      'medicalHistory',
      'socialHistory',
      'familyHistory',
    ],
  },
  {
    tenantId: 'clinic-123',
    name: {
      en: 'Pediatric Intake Form',
      es: 'Formulario de ingreso pediátrico',
    },
    description: {
      en: 'For patients under 18. Includes guardian info.',
      es: 'Para pacientes menores de 18 años. Incluye información del tutor.',
    },
    submitButtonLabel: {
      en: 'Submit pediatric form',
      es: 'Enviar formulario pediátrico',
    },
    isActive: true,
    questionKeys: [
      'name',
      'dob',
      'gender',
      'address',
      'phone',
      'email',
      'guardianName',
      'guardianPhone',
      'insuranceProvider',
      'medicalHistory',
      'allergies',
      'currentMedications',
    ],
  },
  {
    tenantId: 'clinic-123',
    name: {
      en: 'Annual Physical Checkup',
      es: 'Chequeo físico anual',
    },
    description: {
      en: 'Standard annual health assessment',
      es: 'Evaluación anual estándar de salud',
    },
    submitButtonLabel: {
      en: 'Submit health check',
      es: 'Enviar evaluación',
    },
    isActive: true,
    questionKeys: [
      'name',
      'dob',
      'gender',
      'phone',
      'email',
      'currentMedications',
      'medicalHistory',
      'familyHistory',
      'socialHistory',
      'allergies',
    ],
  },
  {
    tenantId: 'clinic-123',
    name: {
      en: 'Covid-19 Screening',
      es: 'Evaluación de COVID-19',
    },
    description: {
      en: 'Pre-screening form for COVID symptoms and exposure',
      es: 'Formulario previo para síntomas y exposición a COVID',
    },
    submitButtonLabel: {
      en: 'Submit screening',
      es: 'Enviar evaluación',
    },
    isActive: true,
    questionKeys: [
      'name',
      'dob',
      'gender',
      'phone',
      'email',
      'symptoms',
      'travelHistory',
      'contactWithCovid',
    ],
  },
  {
    tenantId: 'clinic-123',
    name: {
      en: 'Mental Health Assessment',
      es: 'Evaluación de salud mental',
    },
    description: {
      en: 'Assessment of mood, anxiety, and mental wellbeing',
      es: 'Evaluación del estado de ánimo, ansiedad y bienestar mental',
    },
    submitButtonLabel: {
      en: 'Submit assessment',
      es: 'Enviar evaluación',
    },
    isActive: true,
    questionKeys: [
      'name',
      'dob',
      'gender',
      'currentMedications',
      'mentalHealthSymptoms',
      'familyHistory',
      'socialHistory',
    ],
  },
  {
    tenantId: 'clinic-123',
    name: {
      en: 'Follow-up Visit Form',
      es: 'Formulario de seguimiento',
    },
    description: {
      en: 'Information about symptoms or concerns for follow-up visits',
      es: 'Información sobre síntomas o inquietudes para visitas de seguimiento',
    },
    submitButtonLabel: {
      en: 'Submit follow-up info',
      es: 'Enviar información de seguimiento',
    },
    isActive: true,
    questionKeys: [
      'name',
      'dob',
      'gender',
      'symptoms',
      'currentMedications',
      'recentProcedures',
      'doctorNotes',
    ],
  },
  {
    tenantId: 'clinic-123',
    name: {
      en: 'Pre-Surgical Questionnaire',
      es: 'Cuestionario prequirúrgico',
    },
    description: {
      en: 'Details to prepare for a scheduled surgical procedure',
      es: 'Detalles para preparar un procedimiento quirúrgico programado',
    },
    submitButtonLabel: {
      en: 'Submit surgical prep',
      es: 'Enviar preparación quirúrgica',
    },
    isActive: true,
    questionKeys: [
      'name',
      'dob',
      'gender',
      'phone',
      'email',
      'currentMedications',
      'allergies',
      'medicalHistory',
      'previousSurgeries',
      'anesthesiaConcerns',
    ],
  },
  {
    tenantId: 'clinic-123',
    name: {
      en: 'Specialist Referral Form',
      es: 'Formulario de referencia a especialista',
    },
    description: {
      en: 'Used when a general practitioner refers to a specialist',
      es: 'Utilizado cuando un médico general refiere a un especialista',
    },
    submitButtonLabel: {
      en: 'Submit referral form',
      es: 'Enviar formulario de referencia',
    },
    isActive: true,
    questionKeys: [
      'name',
      'dob',
      'gender',
      'primaryCarePhysician',
      'specialistType',
      'referralReason',
      'medicalHistory',
    ],
  },
];
