export const questionnaireSeedData = [
  {
    tenantId: 'clinic-123',
    name: {
      en: 'Patient Intake Form',
      es: 'Formulario de ingreso del paciente',
    },
    description: {
      en: 'General health and contact information for new patients',
      es: 'Información general de salud y contacto para nuevos pacientes',
    },
    submitButtonLabel: {
      en: 'Submit previsit form',
      es: 'Enviar el formulario',
    },
    isActive: true,
    questionKeys: [
      'name',
      'dob',
      'gender',
      'address',
      'phone',
      'email',
      'emergencyContact',
      'insuranceProvider',
      'insurancePolicyNumber',
      'primaryCarePhysician',
      'allergies',
      'currentMedications',
      'medicalHistory',
      'socialHistory',
      'familyHistory',
    ],
  },
  {
    tenantId: 'clinic-123',
    name: {
      en: 'Dental pre-Visit survey',
      es: 'Encuesta previa a la visita dental',
    },
    description: {
      en: 'General health and contact information for new patients',
      es: 'Información general de salud y contacto para nuevos pacientes',
    },
    submitButtonLabel: {
      en: 'Submit previsit form',
      es: 'Enviar el formulario',
    },
    isActive: true,
    questionKeys: [
      'name',
      'dob',
      'gender',
      'address',
      'phone',
      'email',
      'emergencyContact',
      'insuranceProvider',
      'insurancePolicyNumber',
      'primaryCarePhysician',
      'allergies',
      'currentMedications',
      'medicalHistory',
      'socialHistory',
      'familyHistory',
    ],
  },
  {
    tenantId: 'clinic-123',
    name: {
      en: 'Test visit form',
      es: 'Formulario de prueba',
    },
    description: {
      en: 'General health and contact information for new patients',
      es: 'Información general de salud y contacto para nuevos pacientes',
    },
    submitButtonLabel: {
      en: 'Submit previsit form',
      es: 'Enviar el formulario',
    },
    isActive: true,
    questionKeys: [
      'name',
      'dob',
      'gender',
      'address',
      'phone',
      'email',
      'emergencyContact',
      'insuranceProvider',
      'insurancePolicyNumber',
      'primaryCarePhysician',
      'allergies',
      'currentMedications',
      'medicalHistory',
      'socialHistory',
      'familyHistory',
    ],
  },
];
